# Generated by Django 3.0 on 2021-04-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_userservice_da'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userservice',
            name='carno',
        ),
        migrations.AlterField(
            model_name='userservice',
            name='car_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='service_type',
            field=models.CharField(max_length=100),
        ),
    ]
